<?php

/*
 * ELP 2000-82B · evaluator constants. GENERATED by `astronomy elp2000`
 * in this package.
 */

return [
    // Mean longitude of the Moon, in radians, as a polynomial in T.
    'w1' => [
        3.810344430588308,
        8399.684731773913882,
        -0.000028547283985,
        0.000000032017096,
        -0.000000000153637,
    ],

    // Mean longitude of the lunar perigee, in radians, as a polynomial in T.
    'w2' => [
        1.454788532322509,
        70.993304818359618,
        -0.000185575041600,
        -0.000000218394019,
        0.000000001032702,
    ],

    // Mean longitude of the ascending node, in radians, as a polynomial in T.
    'w3' => [
        2.182439197216840,
        -33.781426356625921,
        0.000030844816020,
        0.000000036967043,
        -0.000000000173854,
    ],

    // General precession in longitude, in arcseconds per julian century. The three mean
    // longitudes above are referred to the INERTIAL equinox, so this has to be added to
    // carry them to the equinox of date.
    'precession' => 5029.0966000000,

    // Arcseconds per radian: the L and B series come in arcseconds.
    'rad' => 206264.8062470964,

    // Scale of the distance series.
    'distance_scale' => 0.9999999999235315,
];
